### ISSUE TITLE
Let's do something new !

### ISSUE THREAD

**Issue by ocoka** [hitode909/vscode-auto-programming#3]
Hello, I've already mentioned your project in other issue (kawamurakazushi/vscode-grep#1), and I also want to thank you for your code and your efforts. And as I mentioned in pointed issue, the real reason of that issue to make something new that I've never seen in other IDE !
_autoprogramming_ is a good idea, but with _git grep_ it doesn't have all the power that it can have. Just imagine if we add an ability to complete from whole history of GIT repository, because of some code, really good code, can be deleted (for any reason, feature split, or unused for now) and later someone want to add the same code, that already was in repo. I think you understand me.

```javascript
let preparedQuery = query.replace(/\s+/g,'.*?');       
                                                            
const command = quote(['git', 'log',                   
 '--format=%aen',                                           
 '--ignore-blank-lines',                                    
 '--pickaxe-regex',                                         
 '-U0',                                                     
 '-w',                                                      
 '-600',                                                    
 '--no-prefix',                                             
 `-S${preparedQuery}`]);
```
))

**Comment by hitode909** [comment]
Hello, Thank you for comment.

> some code, really good code, can be deleted

I don't know your idea is really useful, because
+ Deleted code can be wrong, for example, it may includes typo, calling deleted or deprecated method. I believe living code is better than dead code.
+ Collecting candidates from git log may be heavy process in large repository. The speed of complement is important.

PRs are welcome!
